### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ronag** [programble/errio#5]
```
TypeError: Cannot read property 'options' of undefined
    at Object.exports.toObject (/usr/src/app/node_modules/errio/index.js:92:40)
    at exports.stringify (/usr/src/app/node_modules/errio/index.js:186:33)
    at /usr/src/app/src/server.js:38:23
    at Object.exports.check (/usr/src/app/node_modules/diskusage/index.js:65:13)
    at Timeout._onTimeout (/usr/src/app/src/server.js:31:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by causal-agent** [comment]
What code caused this issue?

Are you using the latest version which includes this previous fix? https://github.com/programble/errio/commit/ed79c5ea30240107421c53a6682540ab7ac2b48c

**Comment by ronag** [comment]
I'm using 1.2.1

**Comment by causal-agent** [comment]
Without more information, I am unable to help.

Feel free to reopen this issue with a repro / test case.

**Comment by ronag** [comment]
@programble: This seems to happen when stringify is passed an integer instead of an error object. Should probably have a check for object in `fromObject`.

**Comment by causal-agent** [comment]
Getting an error from using the interface incorrectly is not a bug.
